namespace: demo-prod
image:
  repository: 435951944183.dkr.ecr.us-west-2.amazonaws.com/ayush-fastapi
  tag: latest

service:
  type: ClusterIP
  port: 8080

replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  ENV_DEPLOYED_ENV: "prod"

networkPolicy:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: fastapi.prod
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fastapi-prod-tls
      hosts:
        - fastapi.prod