namespace: dev-demo
image:
  repository: 435951944183.dkr.ecr.us-west-2.amazonaws.com/ayush-fastapi
  tag: latest

service:
  type: ClusterIP
  port: 8080

replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 90Mi
  limits:
    cpu: 300m
    memory: 128Mi

env:
  ENV_DEPLOYED_ENV: "dev"

ingress:
  enabled: true
  className: nginx

  hosts:
    - host: fastapi.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []
