namespace: dev-demo
image:
  repository: fastapi-uv-docker
  tag: demo-12345

replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 90Mi
  limits:
    cpu: 300m
    memory: 128Mi

env:
  ENV_DEPLOYED_ENV: "dev"
