image:
  repository: fastapi-uv-docker
  tag: local
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 8080

env: {}  # non-sensitive env entries (merged from values-*.yaml)

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
