apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-uv.fullname" . }}
  labels:
    app: {{ include "fastapi-uv.name" . }}
    chart: {{ include "fastapi-uv.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-uv.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-uv.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-placeholder.yaml") . | sha256sum }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "fastapi-uv.fullname" . }}
            - secretRef:
                name: {{ include "fastapi-uv.fullname" . }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
