{{- /* Render a Secret from `.Values.secrets` when values are provided.
      Non-sensitive values should remain in `.Values.env` and will be rendered
      into the ConfigMap. This template renders an empty Secret when no
      secret values are provided so checksum logic continues to work. */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-uv.fullname" . }}
stringData:
{{- if .Values.secrets }}
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- else }}
  {}
{{- end }}
